### ISSUE TITLE
More Precise Throttle control

### ISSUE THREAD

**Issue by xxxyyyqqq12345** [OCESS/orbitx#43]
Currently we can only change throttle by 1 or -1, make it possible to change by number between -1 and 1

**Comment by pmelanson** [comment]
For sure, I think the change I'll make is that

Pressing w is a 1% increase
Pressing shift+w is a 0.1% increase

**Comment by pmelanson** [comment]
A related change I made: I realized we were increasing throttle by 100% every time (throttle += 1), so I changed it so that increasing the throttle using 'w' increases it by 1% (throttle += 0.01).

This may make the engines less powerful. Feel free to change the engine power if that's a problem.

I also added new controls for setting engines to 100% and 0%, see input cheatsheet.

Commit ef4a1d0
