### ISSUE TITLE
Put Altitude(distance to surface) of target and speed at which we are going towards it in the UI

### ISSUE THREAD

**Issue by xxxyyyqqq12345** [OCESS/orbitx#44]
When testing landing, I noticed it's particularly hard to do so since I can't have an accurate estimate of my position relative to Earth, having altitude and speed at which I'm heading towards Earth would be greatly helpful when performing landing

**Comment by pmelanson** [comment]
Added altitude and distance to ref/target in the UI. Also, changed us to be fully WASD (A/D now rotates the ship).

I also noticed we were adding 100% to the throttle each time, (+1) instead of 1% (+0.01), so I changed that as well.

This is in commit 50cb1a7

I'll close this, but if there's still refinement feel free to reopen it
