### ISSUE TITLE
Additional help text "vibrating" when GUI elements change

### ISSUE THREAD

**Issue by pmelanson** [OCESS/orbitx#67]
When GUI text fields change, they sometimes change width. When the widest GUI field changes length, this causes the <table> in the vpython caption to suddenly change width, which makes the location of help text "vibrate"

The <table> should be a fixed size.

**Comment by goodday0404** [comment]
The problem was that the additional text when help text box is toggled increases the width of 3rd column of the table, so that the 3rd column collide with the scene object beside.

Solution applied: 
The 3rd column is merged into 2nd column. The vibrating is gone but the font size of help text become smaller. Because of the number of values on menu side, increasing size of height of each row of table makes the scene object of vector not able to be displayed on full screen. scrolling is needed to see whole vector scene. So I just left the help text displayed in small font size.
